# Generated by Django 3.0.2 on 2020-09-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
