# Generated by Django 3.0.2 on 2020-09-17 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_test_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='data.Answer'),
        ),
    ]
