# Generated by Django 3.0.2 on 2020-09-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_task_answer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='answer_id',
        ),
    ]
